### ISSUE TITLE
clang build failure

### ISSUE THREAD

**Issue by flihp** [01org/tpm2-tss#530] opened 2017-09-12 14:50 UTC
This is probably related to the travis-ci update a few days ago. Looks like they upgraded clang from 3.8 to 3.9 and it's a bit more pedantic. Funny enough the failure occurs when we build cmocka (dependency) not the TSS code:
```
/home/travis/build/01org/tpm2-tss/cmocka-1.0.1/src/cmocka.c:963:21: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
                    a, b);
                    ^
/home/travis/build/01org/tpm2-tss/cmocka-1.0.1/src/cmocka.c:963:24: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
                    a, b);
                       ^
/home/travis/build/01org/tpm2-tss/cmocka-1.0.1/src/cmocka.c:988:21: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
                    a, b);
                    ^
/home/travis/build/01org/tpm2-tss/cmocka-1.0.1/src/cmocka.c:988:24: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
                    a, b);
                       ^
/home/travis/build/01org/tpm2-tss/cmocka-1.0.1/src/cmocka.c:1649:36: error: format specifies type 'void *' but the argument has type 'char *' [-Werror,-Wformat-pedantic]
                                   &guard[j]);
```

**Comment by tstruk** [comment] 2017-09-12 15:28
On 09/12/2017 08:11 AM, Philip Tricca wrote:
> This is probably related to the travis-ci update a few days ago. Looks like they upgraded clang from 3.8 to 3.9 and it's a bit more pedantic. Funny enough the failure occurs when we build cmocka (dependency) not the TSS code:

And what's even more funny is that it passes when you restart just the clang job.

-- 
Tadeusz

**Comment by flihp** [comment] 2017-09-12 18:51
Ugh. The number of travis-ci mysteries is growing. This one the tabrmd is still bugging me: https://github.com/01org/tpm2-abrmd/commit/d1d6a451e00daae579225847ef8435f0c59c5483

**Comment by tstruk** [comment] 2017-09-13 16:56
Fixed with #536

**Closed by tstruk** 2017-09-13 16:56 UTC
Labels: bug

**Comment by tstruk** [comment] 2017-09-15 23:24
@flihp are the problems of travis-ci builds caused by gcc and clang running in parallel?

**Comment by flihp** [comment] 2017-09-16 03:43
not that I know of
